# Practical Assignment - Programming for Data Analysis 2018
By Simona Vasiliauskaite G00263352
# Numpy.Random Package

In this notebook I will answer and discuss following points:
1. The purpose of Numpy.Random package
2. Explanation of 'Simple random data' and 'Permutations' functions
3. Use and purpose of 'Distributions' functions such as uniform, normal, logistic, geometric, exponential and more.
4. Why use seeds in generating pseudorandom numbers.

## 1. Purpose of Numpy.Random package

Before diving deep into the numpy.random package, here are some background information on Numpy as a package.
It is a Python Package, specialized for building and manipulating large, multidimensional arrays. NumPy has built-in functions for linear alegbra and random number generation. 
It's an important library because a lot of the other Python packages such as SciPy, Matplotlib depend on Numpy to function (to a reasonable extent.)

The numpy.random module supplements the built-in Python random with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions. 

Source [Python for Data Analysis by Wes McKinney](https://www.oreilly.com/library/view/python-for-data/9781449323592/ch04.html)

Numpy holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient.

**Numpy array** is a powerful N-dimensional array object which is in the form of rows and columns.

### Import Numpy

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Types of Arrays

**Single-dimensional Numpy Array**

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


**Multi Dimentional Numpy Array**

In [3]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


## 2. Simple Random Data and Permutations

Use of Permutations
shuffle(x)	Modify a sequence in-place by shuffling its contents.
permutation(x)	Randomly permute a sequence, or return a permuted range.

## 3. Examples of Distributions Functions

**Uniform**
**Normal**
**Logistic**
**Geometric**
**Exponential**


## 4. How to Generate Pseudorandom Numbers

RandomState([seed])	Container for the Mersenne Twister pseudo-random number generator.
seed([seed])	Seed the generator.
get_state()	Return a tuple representing the internal state of the generator.
set_state(state)	Set the internal state of the generator from a tuple.

[Docs.SkyPy.org](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html)


### Import Numpy

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(3,)


In [7]:
print(a[0], a[1], a[2])

1 2 3


In [8]:
a[0] = 5                  # Change an element of the array
print(a)

[5 2 3]


In [9]:

#Useful website for simple examples


[URL](http://cs231n.github.io/python-numpy-tutorial/)