# Practical Assignment - Programming for Data Analysis 2018
By Simona Vasiliauskaite G00263352
# Numpy.Random Package

In this notebook I will answer and discuss following points:
1. The purpose of Numpy.Random package
2. Explanation of 'Simple random data' and 'Permutations' functions
3. Use and purpose of 'Distributions' functions such as uniform, normal, logistic, geometric, exponential and more.
4. Why use seeds in generating pseudorandom numbers.

## 1. Purpose of Numpy.Random package

Before diving deep into the numpy.random package, here are some background information on Numpy as a package.
It is a Python Package, specialized for building and manipulating large, multidimensional arrays. NumPy has built-in functions for linear alegbra and random number generation. 
It's an important library because a lot of the other Python packages such as SciPy, Matplotlib depend on Numpy to function (to a reasonable extent.)

The numpy.random module supplements the built-in Python random with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions.  Source [Python for Data Analysis by Wes McKinney](https://www.oreilly.com/library/view/python-for-data/9781449323592/ch04.html)


Numpy holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient.

**Numpy array** is a powerful N-dimensional array object which is in the form of rows and columns.

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

## Types of Arrays

**Single-dimensional Numpy Array**

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


**Multi Dimentional Numpy Array**

In [3]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


## 2. Permutations & Simple Random Data

## 2.1
What is permutation?

A permutation is a method to calculate the number of events occurring where order matters.

Use of Permutations
* **permutation(x)**	Randomly permute a sequence, or return a permuted range.
* **shuffle(x)**	Modify a sequence in-place by shuffling its contents.

In [4]:
#A Python program to print all permutations using library function 
from itertools import permutations 
  
# Get all permutations of [1, 2, 3] 
p = permutations([1, 2, 3]) 
  
# Print the obtained permutations 
for i in list(p): 
    print(i) 

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


What does Shuffle function do?

The method shuffle() randomizes the items of a list in place.

In [5]:
#Testing a Python library to shuffle all values
from random import shuffle

x = [12, 15, 77, 298];

# Shuffle and print the outcome
shuffle(x)
print ("Reshuffled values : ", x)

Reshuffled values :  [77, 15, 12, 298]


In [6]:
# Try the shuffle function with strings

names = ["Simona", "Elena", "Pat", "Dave"]

shuffle(names) # shuffle all strings

print ("New shuffled name order : ", names) # print shuffled strings


New shuffled name order :  ['Pat', 'Dave', 'Simona', 'Elena']


## 2.2 

Sample Random Data

In [7]:
import random # import random function

**random.sample**

sample() is an inbuilt function of random module in Python that returns a particular length list of items chosen from the sequence i.e. list, tuple, string or set. Used for random sampling without replacement.

In [8]:

# Prints list of random items of length 3 from the given list. 
list1 = [1, 2, 3, 4, 5, 6]  
print("With list:", random.sample(list1, 3)) 
  
# Prints list of random items of length 4 from the given string.  
string = "Computer"
print("With string:", random.sample(string, 4)) 
  
# Prints list of random items of length 3 from the given tuple. 
tuple1 = ("college" , "work" , "pc" , "study" , "science") 
print("With tuple:", random.sample(tuple1, 3)) 
  
  
# Prints list of random items of length 3 from the given set. 
set1 = {"a", "b", "c", "d", "e"} 
print("With set:", random.sample(set1, 3)) 

With list: [6, 2, 5]
With string: ['o', 'm', 'u', 'p']
With tuple: ['study', 'work', 'college']
With set: ['d', 'b', 'c']


**random.randint**

Return a random element from the non-empty sequence seq. If seq is empty, raises IndexError.

Randint accepts two parameters: a lowest and a highest number.

In [14]:
# Generate integers between 1,5. The first value should be less than the second.

a = random.randint(0, 5)
print(a)

5


**random.choice**

In [15]:
import random

foo = ['a', 'b', 'c', 'd', 'e']
print(random.choice(foo))

e


## 3. Examples of Distributions Functions

**Uniform**
**Normal**
**Logistic**
**Geometric**
**Exponential**


## 4. Use of Seed

Random number generation (RNG) is the process by which a string of random numbers may be drawn. The numbers are not completely random for several reasons.

1. They are drawn from a probability distribution. The most common one is the uniform distribution on the domain  0≤x<1 , i.e., random numbers between zero and one. 

2. In most computer applications, the random numbers are actually pseudorandom. They depend entirely on an input seed and are then generated by a deterministic algorithm from that seed. [Source](http://justinbois.github.io/bootcamp/2016/lessons/l26_random_number_generation.html)


To demonstrate that random number generation is deterministic, we will explicitly seed the random number generator

In [ ]:
# Seed the RNG
np.random.seed(25)

# Generate random numbers
np.random.random(size=5)

In [ ]:
# Re-seed the RNG
np.random.seed(25)

# Generate random numbers
np.random.random(size=5)

The random numbers are exactly the same. If we choose a different seed, we get totally different random numbers.

### Import Numpy

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))

In [ ]:
print(a.shape)

In [ ]:
print(a[0], a[1], a[2])

In [ ]:
a[0] = 5                  # Change an element of the array
print(a)

In [ ]:

#Useful website for simple examples


[URL](http://cs231n.github.io/python-numpy-tutorial/)