# Practical Assignment - Programming for Data Analysis 2018
By Simona Vasiliauskaite G00263352
# Numpy.Random Package

In this notebook I will answer and discuss following points:
1. The purpose of Numpy.Random package
2. Explanation of 'Simple random data' and 'Permutations' functions
3. Use and purpose of 'Distributions' functions such as uniform, normal, logistic, geometric, exponential and more.
4. Why use seeds in generating pseudorandom numbers.

## 1. Purpose of Numpy.Random package

Before diving deep into the numpy.random package, here are some background information on Numpy as a package.
It is a Python Package, specialized for building and manipulating large, multidimensional arrays. NumPy has built-in functions for linear alegbra and random number generation. 
It's an important library because a lot of the other Python packages such as SciPy, Matplotlib depend on Numpy to function (to a reasonable extent.)

The numpy.random module supplements the built-in Python random with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions.  Source [Python for Data Analysis by Wes McKinney](https://www.oreilly.com/library/view/python-for-data/9781449323592/ch04.html)


Numpy holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient.

**Numpy array** is a powerful N-dimensional array object which is in the form of rows and columns.

In [1]:
import numpy as np 
import matplotlib.pyplot as plt

## Types of Arrays

**Single-dimensional Numpy Array**

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


**Multi Dimentional Numpy Array**

In [3]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


## 2. Permutations & Simple Random Data

What is permutation?

A permutation is a method to calculate the number of events occurring where order matters.

Use of Permutations
* **permutation(x)**	Randomly permute a sequence, or return a permuted range.
* **shuffle(x)**	Modify a sequence in-place by shuffling its contents.

In [4]:
#A Python program to print all permutations using library function 
from itertools import permutations 
  
# Get all permutations of [1, 2, 3] 
p = permutations([1, 2, 3]) 
  
# Print the obtained permutations 
for i in list(p): 
    print(i) 

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


What does Shuffle function do?

The method shuffle() randomizes the items of a list in place.

In [5]:
#Testing a Python library to shuffle all values
from random import shuffle

x = [12, 15, 77, 298];

# Shuffle and print the outcome
shuffle(x)
print ("Reshuffled values : ", x)

Reshuffled values :  [77, 15, 298, 12]


In [6]:
# Try the shuffle function with strings

names = ["Simona", "Elena", "Pat", "Dave"]

shuffle(names) # shuffle all strings

print ("New shuffled name order : ", names) # print shuffled strings


New shuffled name order :  ['Pat', 'Simona', 'Elena', 'Dave']


## 3. Examples of Distributions Functions

**Uniform**
**Normal**
**Logistic**
**Geometric**
**Exponential**


## 4. How to Generate Pseudorandom Numbers

RandomState([seed])	Container for the Mersenne Twister pseudo-random number generator.
seed([seed])	Seed the generator.
get_state()	Return a tuple representing the internal state of the generator.
set_state(state)	Set the internal state of the generator from a tuple.

[Docs.SkyPy.org](https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html)


### Import Numpy

In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))

<class 'numpy.ndarray'>


In [9]:
print(a.shape)

(3,)


In [10]:
print(a[0], a[1], a[2])

1 2 3


In [11]:
a[0] = 5                  # Change an element of the array
print(a)

[5 2 3]


In [12]:

#Useful website for simple examples


[URL](http://cs231n.github.io/python-numpy-tutorial/)